import type { Metadata } from "next";
import { Josefin_Sans, Roboto } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Test Pike",
  description: "Generated by create next app",
};

const josefin = Josefin_Sans({
  subsets: ["latin"],
  display: "auto",
  variable: "--font-sans",
});
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "auto",
  variable: "--font-title",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" data-lt-installed="true">
      <body className={`${josefin.className} ${roboto.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
